config/routes.rb
Rails.application.routes.draw do
  get 'playlists/timeline'
  get 'playlists/index'
  get 'playlists/add_memory'
  get 'playlists/edit' => 'playlists/edit', :as => :edit
  get 'welcome/index'
  get 'players/index'
  get 'playlists/destroy'
  get 'friends/index'
  get 'players/play'
  get 'players/web_player'
  get 'users/dashboard'
  get 'friends/unsubscribe'
  get 'shared/index'
  get 'analytics/index'
  get 'analytics/destroy_timeline'
  get 'analytics/destroy_moment'
  get 'tutorial/index'
  get 'tutorial/timeline'
  get 'tutorial/destroy'

  post 'playlists/timeline'
  post 'playlists/edit'
  post 'playlists/add_memory'
  post 'playlists/index'

  resources :users

  get '/auth/spotify/callback', to: 'users#login'

  root 'welcome#index'
end

app/models/playlist.rb
class Playlist < ApplicationRecord
end

app/controllers/playlists_controller.rb
require 'json'
require 'time'
require 'net/http'
require 'open-uri'
require 'json'

class PlaylistsController < ApplicationController
  protect_from_forgery except: :find_track_for_memory
  protect_from_forgery except: :add_memory

  def index
    if params[:new_item] != nil
      @focused_memory = params[:new_item].to_s.gsub(/[^a-z ]/, '').gsub(/\s+/, "")
    end

    begin
      @user = RSpotify::User.new(session[:user])
    rescue NoMethodError => e
      Rails.logger.info "users first time >:)"
      @user = RSpotify::User.new(session[:me])
      session[:user] = session[:me]
    end

    @current_timeline = Timeline.where(:creator => @user.email)
    @playlists =  @user.playlists
    @tracks = Track.where(:username => @user.email).order(:memory_date)
    @tracks_count = Track.where(:username => @user.email).length
    @moments = Moment.where(:user => @user.email)
    @moments_count = Moment.where(:user => @user.email).length

    @months = {}

    @moments.each do |m|
      @months[m.start_date.month] = @months[m.start_date.month].to_i + 1
    end

    @tracks_array = @tracks.to_a #tracks (memories)

    @tlhash = {} # {month-int => [track, playlist, track..]} each array is sorted by date later..
    @momenthash = {}
    @playlists.each do |p|
      if @tlhash[p.tracks_added_at[p.tracks_added_at.keys[0]].month] == nil
        @tlhash[p.tracks_added_at[p.tracks_added_at.keys[0]].month] = []
      end
      @months[p.tracks_added_at[p.tracks_added_at.keys[0]].month] = @months[p.tracks_added_at[p.tracks_added_at.keys[0]].month].to_i + 1
      if @tracks_array.length > 0
        @tracks_array.each_with_index do |t, i|
          if @tlhash[t.memory_date.month] == nil
            @tlhash[t.memory_date.month] = []
          end
          new_track = []
          new_track << t #track memory
          #match track to track data by looking more into playlist
          matched_playlist = []
          @playlists.each do |pp|
            if pp.name.eql? t.playlist_name
              matched_playlist = pp
            end
          end

          matched_playlist.tracks.each do |pt| #match track name to rspotify track object
            if pt.name.eql? t.title
              new_track << pt #add track object in along with memory
            end
          end
          moment_item = false
          @moments.each do |m|
            if t.memory_date <= m.end_date and t.memory_date >= m.start_date
              new_track << m
              moment_item = true
            end
          end

          if moment_item == true
            if @momenthash[new_track[2].start_date.month] == nil
              @momenthash[new_track[2].start_date.month] = []
            end
            @momenthash[new_track[2].start_date.month] << new_track
          else
            @tlhash[t.memory_date.month] << new_track
            @months[t.memory_date.month] = @months[t.memory_date.month].to_i + 1
          end
          @tracks_array.delete_at(i)
        end
      end
      @tlhash[p.tracks_added_at[p.tracks_added_at.keys[0]].month] << p
    end

    #iterate over each entry in tl hash and sort array by date

    @tlhash.each do |k, v| # v - array
      moment_index = 0
      items_sorted = []
      datehash = {}
      month_moment = @momenthash[k]
      v.each do |i|
        if i.class == RSpotify::Playlist
          playlistday = i.tracks_added_at.values[0].to_date.day
          if datehash[playlistday] == nil
            datehash[playlistday] = [] #make each date in hash an array in case items share a date
          end
          datehash[playlistday] << i
        else #memory/moment-item
          itemday = i[0].memory_date.day
          if datehash[itemday] == nil
            datehash[itemday] = []
          end
          datehash[itemday] << i
        end
      end

      (1..datehash.keys.max).each do |day| #iterate over every day in month
        if datehash[day] != nil
          datehash[day].reverse.each do |j| #iterate over items from that day (usually one, but someone could have multiple things on the same day)
            items_sorted << j #if item in that day plop it in
          end
        end
      end
      @tlhash[k] = [items_sorted, month_moment]
    end

    @months_colors = {1 => "#5f7ed4", 2 => "#d45f80", 3 => "#5fd488", 4 => "#5fced4", 5 => "#d4d25f", 6 => "#d4945f", 7 => "#b15fd4", 8 => "#d4765f", 9 => "#5fd4ad", 10 => "#d49d5f", 11 => "#735fd4", 12 => "#e5f2a0"}

    @playlists_h = {}
    @playlists.each do |p|
      track_names = []
      p.tracks.each do |t|
        track_names << t.name
      end
      @playlists_h[p.name] = track_names
    end

    if request.method.eql? "POST"
      if params[:track].eql? nil
        if params[:moment].eql? nil
          params.require(:timeline).permit!
          current_subs = Timeline.where(:creator => @user.email)[0].subscribers.to_s
          tid = Timeline.where(:creator => session[:user]['email'])[0].id
          Timeline.update(tid, :subscribers => current_subs + "," + params[:timeline][:subscribers].to_s)
          Rails.logger.info "SHARING"
        else
          params.require(:moment).permit!
          uhohs = ""
          dont_save = false

          if params[:moment][:name].length == 0
            uhohs += "no name entered, "
            dont_save = true
          end
          if params[:moment][:start_date].length == 0
            uhohs += "no start date, "
            dont_save = true
          end
          if params[:moment][:end_date].length == 0
            uhohs += "no end date, "
            dont_save = true
          end

          if dont_save
            redirect_to :action => "index", :controller => "playlists", :errors_moment => uhohs
          else
            Moment.new(params[:moment]).save
            redirect_to :action => "index", :controller => "playlists", :new_item => params[:moment][:name].gsub(/[^a-z ]/, '').gsub(/\s+/, "")
          end
        end
      else
        Rails.logger.debug "saving new track"
        Rails.logger.debug params[:track]
        params.require(:track).permit!
        #check form
        uhohs = ""
        dont_save = false
        if params[:track][:title].length == 0
          uhohs += "no song selected,"
          dont_save = true
        end
        if params[:track][:memory_date].length == 0
          uhohs += "no date,"
          dont_save = true
        end
        if params[:track][:memory].length == 0
          uhohs += "no memory written,"
          dont_save = true
        end
        # if params[:track][:imageurl].length == 0
        #   uhohs += "no image"
        #   dont_save = true
        # end
        if !dont_save
          t = Track.new(params[:track])
          t.image.attach(params[:track][:image])
          t.save
          redirect_to :action => "index", :controller => "playlists", :new_item => params[:track][:title].gsub(/[^a-z ]/, '').gsub(/\s+/, "")
        else
          redirect_to :action => "index", :controller => "playlists", :errors_memory => uhohs
        end
      end
    end
    Rails.logger.info @months.inspect
  end

  def timeline
    if request.method.eql? "POST"
      if params[:track][:image] == nil
        ttt = Track.where(:title => params[:track][:title], :username => params[:track][:username])[0].id
        Track.update(ttt, :memory => params[:track][:memory], :imageurl => params[:track][:imageurl], :memory_date => params[:track][:memory_date])
        redirect_to :action => "index", :controller => "playlists", :new_item => params[:track][:title].gsub(/[^a-z ]/, '').gsub(/\s+/, "")
      else
        params.require(:track).permit(:title, :image, :playlist_name)
        Rails.logger.info "attaching"
        Rails.logger.info params[:track][:image]
        track = Track.where(:username => session[:user]['email'], :title => params[:track][:title])[0]
        Rails.logger.info "track hehe"
        Rails.logger.info track.inspect
        track.image.attach(params[:track][:image])
        redirect_to :action => "timeline", :controller => "playlists", :playlist => params[:track][:playlist_name], :track => params[:track][:title]
      end
    else
      @playlist_name = params[:playlist]
      @track_name = params[:track]
      @user = RSpotify::User.new(session[:user])
      @playlists = @user.playlists
      @current_timeline = Timeline.where(:creator => @user.email)

      @playlists.each do |p|
        if p.name.eql? @playlist_name
          @playlist = p
          break
        end
      end

      @playlist.tracks.each do |t|
        if t.name.eql? @track_name
          @track = t
          break
        end
      end

      @tracks = Track.where(:username => @user.email, :playlist_name => @playlist_name, :title => @track_name)

      @playlists_h = {}
      @playlists.each do |p|
        track_names = []
        p.tracks.each do |t|
          track_names << t.name
        end
        @playlists_h[p.name] = track_names
      end
    end
  end

  def edit
    @track = Track.where(username: session[:user]['email'], playlist_name: params[:playlist_name], title: params[:track_name]).order(:title)

    if request.method.eql? "POST"
      params.require(:track).permit!
      if Track.where(username: params[:track][:username], title: params[:track][:title], playlist_name: params[:track][:playlist_name]).empty?
        @track = Track.new(params[:track])
        @track.save
        @action = "created"
      else
        @track = Track.where(username: params[:track][:username], title: params[:track][:title], playlist_name: params[:track][:playlist_name])
        @track.update(memory: params[:track][:memory], imageurl: params[:track][:imageurl])
        @action ="updated"
      end

      @user = RSpotify::User.new(session[:user])
      redirect_to :action => "timeline", :playlist => params[:track][:playlist_name]
    else

    end
  end

  def update

  end

  def create
    track = new Track()
  end

  def destroy
    @user = RSpotify::User.new(session[:user])

app/helpers/playlists_helper.rb
module PlaylistsHelper

  def color_mind(tlhash)
    @month_color_scheme = {}
    #get a color scheme for each month in the tlhash..
    image = Magick::ImageList.new
    tlhash.keys.each do |k|
      pixels = [] #pixels to be dumped into colormind
      tlhash[k].each do |t|
        if t.class != RSpotify::Playlist
          urlimage = open(t[1].album.images[0]['url'])
          image.from_blob(urlimage.read)
          count = 0
          image.each_pixel do |pixel, c, r|
            begin
              pixels << [pixel.to_color[1..2].to_i(16), pixel.to_color[3..4].to_i(16), pixel.to_color[5..6].to_i(16)]
              count = count + 1
              if count > 100
                break
              end
            rescue ArgumentError => e
              Rails.logger.info "oopsies!"
              break
            end
          end
        end
      end

      data = {
        :model => "default",
        :input => pixels
      }

      url = URI.parse('http://colormind.io/api/')
      req = Net::HTTP::Get.new(url.to_s, {'Content-Type': 'text/json'})
      req.body = data.to_json
      res = Net::HTTP.start(url.host, url.port) {|http|
        http.request(req)
      }
      color_results = JSON.parse(res.body)['result'] #2d array of 5 rgb values [[r,g,b], [], ...]
      @month_color_scheme[k] = color_results
    end

    Rails.logger.info @month_color_scheme.inspect
  end
  
end

app/views/playlists/_add_image_form.html.erb
<%= form_with scope: :track, url: playlists_timeline_path, local: true do |form| %>
  <p><%= form.file_field :image %><p>
  <p><%= form.hidden_field :title, :value => @tracks[0].title %><p>
  <p><%= form.hidden_field :playlist_name, :value => @tracks[0].playlist_name %><p>
  <p><%= form.submit %></p>
<% end %>

app/views/playlists/_edit_memory_form.html.erb
<%= form_with scope: :track, url: playlists_timeline_path, local: true do |form| %>
  <p>
    <%= form.label :memory %><br>
    <%= form.text_area :memory, :value => @tracks[0].memory %>
  </p>

  <p>
    <%= form.label :memory_date %><br>
    <%= form.date_field :memory_date, :value => @tracks[0].memory_date %>
  </p>

  <p>
    <%= form.label "Image" %><br>
    <%= form.file_field :image, :value => @tracks[0].image %>
  </p>

  <p>
    <%= form.hidden_field :imageurl, :value => @tracks[0].imageurl %>
  </p>

  <p>
    <%= form.hidden_field :playlist_name, :value => @tracks[0].playlist_name %>
  </p>

  <p>
    <%= form.hidden_field :title, :value => @tracks[0].title %>
  </p>

  <p>
    <%= form.hidden_field :username, :value => session[:user]['email'] %>
  </p>

  <p>
    <%= form.hidden_field :timeline_id, :value => @current_timeline[0].id %>
  </p>

  <p>
    <%= form.submit "Save Memory", {:class => "btn btn-primary"}%>
  </p>
<% end %>

app/views/playlists/_memory_form.html.erb
<a style="float:right" href="https://github.com/Hermje/re-verse/blob/master/README.md#memories" class="btn btn-primary">Help</a>
<%= form_with scope: :track, url: playlists_index_path, local: true do |form| %>
  <%= form.label "Select song from playlist:" %>
  <%= form.select :playlist_name, @playlists.collect {|p| [p.name, p.name]}, {include_blank: true}, {onChange: "updateTrackList()"}%>

  <div id='track-select'>
    <% @playlists_h.keys.each do |k| %>
      <div id="<%=k%>" style="display:none">
        <% @playlists_h[k].each do |t| %>
          <%= form.radio_button :title, t %><%=t%><br>
        <% end %>
      </div>
    <% end %>
  </div>

  <p>
    <%= form.label "Describe the event this song reminds you of" %><br>
    <%= form.text_area :memory %>
  </p>

  <p>
    <%= form.label "Date of memory" %><br>
    <%= form.date_field :memory_date %>
  </p>

  <p>
    <%= form.label "Upload image related to memory (optional)" %><br>
    <%= form.file_field :image %>
  <p>

  <p>
    <%= form.hidden_field :imageurl, :value => "fart" %>
  </p>

  <script language="javascript" type="text/javascript">
    var previousPl = ""
    function updateTrackList()
    {
      var e = document.getElementById('track_playlist_name');
      var playlistName = e.options[e.selectedIndex].value;
      document.getElementById(playlistName).style.display = "block";
      try {
        document.getElementById(previousPl).style.display = "none";
      } catch (e) {
        console.log(previousPl);
      }
      previousPl = playlistName;
    }
  </script>

  <p>
    <%= form.hidden_field :username, :value => session[:user]['email'] %>
  </p>

  <p>
    <%= form.hidden_field :timeline_id, :value => @current_timeline[0].id %>
  </p>

  <p>
    <%= form.submit "Save Memory", {:class => "btn btn-primary"}%>
  </p>
<% end %>

app/views/playlists/_moment_form.html.erb
<a style="float:right" href="https://github.com/Hermje/re-verse/blob/master/README.md#moments" class="btn btn-primary">Help</a>
<%= form_with scope: :moment, url: playlists_index_path, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :description %><br>
    <%= form.text_field :description %>
  </p>
  <p>
    <%= form.label :start_date %><br>
    <%= form.date_field :start_date %>
  </p>

  <p>
    <%= form.label :end_date %><br>
    <%= form.date_field :end_date %>
  </p>

  <p>
    <%= form.hidden_field :user, :value => session[:user]['email'] %>
  </p>

  <p>
    <%= form.hidden_field :timeline_id, :value => @current_timeline[0].id %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/playlists/_share_timeline_form.html.erb
<%= form_with scope: :timeline, url: playlists_index_path, local: true do |form| %>
  <h3><%= @current_timeline[0].name %>'s Timeline</h3>

  <p>
    <p>Friend Email:</p><br>
    <%= form.text_field :subscribers %>
  </p>

  <p>
    <%= form.hidden_field :creator, :value => session[:user]['email'] %>
  </p>

  <p>
    <%= form.hidden_field :name, :value => session['user']['email'] %><br>
  </p>

  <p>
    <%= form.submit "share", {:class => "btn btn-primary"}%>
  </p>
<% end %>

app/views/playlists/edit.html.erb
<div id="modal-body">
  <% if request.method.eql? "GET" %>

    <%= link_to 'back', {:controller => 'playlists', :action => 'timeline', :playlist => params[:playlist_name], :offset => params[:offset]} %>
    <h1>Add Memory</h1>

    <%= form_with scope: :track, url: playlists_edit_path, local: true do |form| %>
      <% if params[:update].eql? 'yaw' %>
        <p>
          <%= form.label :memory %><br>
          <%= form.text_area :memory, :value => @track[0].memory %>
        </p>

        <p>
          <%= form.label :imageurl %><br>
          <%= form.text_field :imageurl, :value => @track[0].imageurl %>
        </p>
      <% else %>
        <p>
          <%= form.label :memory %><br>
          <%= form.text_area :memory %>
        </p>

        <p>
          <%= form.label :imageurl %><br>
          <%= form.text_field :imageurl %>
        </p>
      <% end %>

      <p>
        <%= form.hidden_field :playlist_name, :value => params[:playlist_name] %>
      </p>

      <p>
        <%= form.hidden_field :username, :value => session[:user]['email'] %>
      </p>

      <p>
        <%= form.hidden_field :title, :value => params[:track_name] %>
      </p>

      <p>
        <%= form.submit %>
      </p>
    <% end %>
  <% else %>
    <h1>memory <%= @action %></h1>
    <%=link_to 'back', {:controller => "playlists", :action => "timeline", :user => RSpotify::User.find(params[:track][:username]).to_hash, :playlist => params[:track][:playlist_name]} %>
  <% end %>
</div>

app/views/playlists/find_track_for_memory.html.erb
<script language="javascript" type="text/javascript">
  function updateTrackList()
  {
    var e = document.getElementById('playlist-select');
    var playlistName = e.options[e.selectedIndex].value;
    document.getElementById(playlistName).style.display = "block";
  }
</script>

<select id="playlist-select" onchange="updateTrackList()">
  <% @playlists.each do |p| %>
    <option value="<%= p.name %>"><%= p.name %></option>
  <% end %>
</select>

<%= form_with url: playlists_add_memory_path, local: true do |form| %>
  <div id='track-select'>
    <% @playlists_h.keys.each do |k| %>
      <div id="<%=k%>" style="display:none">
        <% @playlists_h[k].each do |t| %>
          <%= form.radio_button k, t %><%=t%><br>
        <% end %>
      </div>
    <% end %>
  </div>
  <%= form.submit %>
<% end %>

app/views/playlists/index.js.erb
$(document).ready(function() {
  $("#timeline-container").scrollTo(".<%= @focused_item %>");
});

app/views/playlists/timeline.html.erb
<div class="modal fade" id="editMemory" tabindex="-1" role="dialog" aria-labelledby="editMemoryModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editMemoryModalLabel">Edit Memory</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">x</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render "playlists/edit_memory_form" %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="addImage" tabindex="-1" role="dialog" aria-labelledby="addImageModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addImageModalLabel">Edit Memory</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">x</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render "playlists/add_image_form" %>
      </div>
    </div>
  </div>
</div>


<nav class="navbar navbar-dark shadow">
  <% if @tracks[0] != nil %>
    <a href="/playlists/index" class="navbar-brand mb-0 h1"><%= @tracks[0].memory_date %> - <%= @tracks[0].title %></a>
  <% end %>
  <ul class="nav nav-pills">
    <li class='nav-item'><%= link_to "back", {:controller => 'playlists', :action => 'index'} %></li>
    <li class='nav-item'><%= link_to "edit", "#editMemory", {'data-toggle' => 'modal', 'id' => 'edit', 'class' => 'nav-link', 'data-target' => '#editMemory', 'id' => 'edit-button'} %></li>
  </ul>
</nav>

<div id="current-memory">
  <div id="track-art-container">
    <% if @tracks[0].image.attached? %>
      <img class='track-art' src=<%= url_for(@tracks[0].image) %>/>
    <% else %>
      <%= link_to "add image", "#addImage", {'data-toggle' => 'modal', 'id' => 'imageadd', 'class' => 'nav-link', 'data-target' => '#addImage', 'id' => 'image-button'} %>
    <% end %>
  </div>
</div>

<div id="memory-info">
  <% unless @tracks[0].nil? %>
    <h4 class='memory'><%= @tracks[0].memory_date %></h4>
    <h4 class='memory'><%= @tracks[0].memory %></h4>
  <% end %>
</div>

<p></p>
<!-- <p id='play' class='button'><%=link_to 'play', {:controller => 'players', :action => 'play', :playlist_name => @playlist_name, :track_name => @track_name} %></p> -->

<% unless @track.nil? %>
  <style>
    body {
      background:
        linear-gradient(
          rgba(30, 32, 35, 0.45),
          rgba(30, 32, 35, 0.45)
        ),
        url('<%= @track.album.images[1]['url'] %>') !important;
    }
  </style>
<% end %>